version: 2
jobs:
 production:
   machine:
    image: ubuntu-2004:202111-02
   resource_class: large
   parallelism: 4
   steps:
     - checkout
     - run:
           name: "Build rmarkdown packages container"
           command: |
            docker build -f Dockerfile.production -t cmzambranat/production:4.1.3 .
     - deploy:
           name: "Push to Docker Hub"
           command: |
              if [ "${CIRCLE_BRANCH}" == "main" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push cmzambranat/production:4.1.3
              fi
workflows:
   version: 2
   commit:
     jobs:
       - production
